/**
 * R17.9L.3 — DepositSession lifecycle states and allowed transitions.
 * Domain only. No TON, no GameEscrow, no deployment gate.
 */

export const DEPOSIT_SESSION_STATUS = Object.freeze({
    CREATED: "CREATED",
    PLAYER_BINDING: "PLAYER_BINDING",
    AWAITING_FUNDS: "AWAITING_FUNDS",
    PARTIALLY_FUNDED: "PARTIALLY_FUNDED",
    DEPOSIT_FULL: "DEPOSIT_FULL",
    DEPLOY_AUTHORIZED: "DEPLOY_AUTHORIZED",
    GAME_CONTRACT_CREATED: "GAME_CONTRACT_CREATED",
    RELEASED: "RELEASED",
    REIMBURSED: "REIMBURSED",
    EXPIRED: "EXPIRED",
    REFUNDING: "REFUNDING",
    REFUNDED: "REFUNDED"
});

export const DEPOSIT_SESSION_TRANSITIONS = Object.freeze({
    [DEPOSIT_SESSION_STATUS.CREATED]: Object.freeze([
        DEPOSIT_SESSION_STATUS.PLAYER_BINDING
    ]),
    [DEPOSIT_SESSION_STATUS.PLAYER_BINDING]: Object.freeze([
        DEPOSIT_SESSION_STATUS.AWAITING_FUNDS
    ]),
    [DEPOSIT_SESSION_STATUS.AWAITING_FUNDS]: Object.freeze([
        DEPOSIT_SESSION_STATUS.PARTIALLY_FUNDED,
        DEPOSIT_SESSION_STATUS.EXPIRED
    ]),
    [DEPOSIT_SESSION_STATUS.PARTIALLY_FUNDED]: Object.freeze([
        DEPOSIT_SESSION_STATUS.DEPOSIT_FULL,
        DEPOSIT_SESSION_STATUS.EXPIRED
    ]),
    [DEPOSIT_SESSION_STATUS.DEPOSIT_FULL]: Object.freeze([
        DEPOSIT_SESSION_STATUS.DEPLOY_AUTHORIZED
    ]),
    [DEPOSIT_SESSION_STATUS.DEPLOY_AUTHORIZED]: Object.freeze([
        DEPOSIT_SESSION_STATUS.GAME_CONTRACT_CREATED
    ]),
    [DEPOSIT_SESSION_STATUS.GAME_CONTRACT_CREATED]: Object.freeze([
        DEPOSIT_SESSION_STATUS.RELEASED,
        DEPOSIT_SESSION_STATUS.REIMBURSED
    ]),
    [DEPOSIT_SESSION_STATUS.EXPIRED]: Object.freeze([
        DEPOSIT_SESSION_STATUS.REFUNDING
    ]),
    [DEPOSIT_SESSION_STATUS.REFUNDING]: Object.freeze([
        DEPOSIT_SESSION_STATUS.REFUNDED
    ]),
    [DEPOSIT_SESSION_STATUS.RELEASED]: Object.freeze([]),
    [DEPOSIT_SESSION_STATUS.REIMBURSED]: Object.freeze([]),
    [DEPOSIT_SESSION_STATUS.REFUNDED]: Object.freeze([])
});

export const TERMINAL_DEPOSIT_SESSION_STATUSES = Object.freeze([
    DEPOSIT_SESSION_STATUS.RELEASED,
    DEPOSIT_SESSION_STATUS.REIMBURSED,
    DEPOSIT_SESSION_STATUS.REFUNDED
]);

export const RESTORABLE_DEPOSIT_SESSION_STATUSES = Object.freeze([
    DEPOSIT_SESSION_STATUS.CREATED,
    DEPOSIT_SESSION_STATUS.PLAYER_BINDING,
    DEPOSIT_SESSION_STATUS.AWAITING_FUNDS,
    DEPOSIT_SESSION_STATUS.PARTIALLY_FUNDED,
    DEPOSIT_SESSION_STATUS.DEPOSIT_FULL,
    DEPOSIT_SESSION_STATUS.DEPLOY_AUTHORIZED,
    DEPOSIT_SESSION_STATUS.GAME_CONTRACT_CREATED,
    DEPOSIT_SESSION_STATUS.EXPIRED,
    DEPOSIT_SESSION_STATUS.REFUNDING
]);

export function canTransitionDepositStatus(fromStatus, toStatus) {

    const allowed = DEPOSIT_SESSION_TRANSITIONS[fromStatus] ?? [];

    return allowed.includes(toStatus);

}

export function isDepositSessionTerminal(status) {

    return TERMINAL_DEPOSIT_SESSION_STATUSES.includes(status);

}

export function isRestorableDepositSessionStatus(status) {

    return RESTORABLE_DEPOSIT_SESSION_STATUSES.includes(status);

}
