export const EVENT_TYPES = Object.freeze({
    TEST_EVENT: "TEST_EVENT",

    CATALOG_LOADED: "CATALOG_LOADED",

    CONFIGURATION_READY: "CONFIGURATION_READY",
    CONFIGURATION_REMOVED: "CONFIGURATION_REMOVED",

    GAME_CREATED: "GAME_CREATED",
    GAME_INITIALIZED: "GAME_INITIALIZED",
    GAME_STARTED: "GAME_STARTED",
    GAME_STATE_CHANGED: "GAME_STATE_CHANGED",
    GAME_STATE_REJECTED: "GAME_STATE_REJECTED",

    CLOCK_STARTED: "CLOCK_STARTED",
    CLOCK_PAUSED: "CLOCK_PAUSED",
    CLOCK_RESUMED: "CLOCK_RESUMED",
    CLOCK_STOPPED: "CLOCK_STOPPED",
    PHASE_TIMEOUT: "PHASE_TIMEOUT",

    GAME_FINISHED: "GAME_FINISHED",
    GAME_DESTROYED: "GAME_DESTROYED",

    ROOM_CREATED: "ROOM_CREATED",
    ROOM_FULL: "ROOM_FULL",
    ROOM_LOCKED: "ROOM_LOCKED",
    ROOM_DESTROYED: "ROOM_DESTROYED",

    PLAYER_JOINED: "PLAYER_JOINED",
    PLAYER_LEFT: "PLAYER_LEFT",
    PLAYER_CREATED: "PLAYER_CREATED",
    PLAYER_CONNECTED: "PLAYER_CONNECTED",
    PLAYER_DISCONNECTED: "PLAYER_DISCONNECTED",
    PLAYER_RUNTIME_UPDATED: "PLAYER_RUNTIME_UPDATED",
    PLAYER_REMOVED: "PLAYER_REMOVED",

    BUTTON_PRESS: "BUTTON_PRESS",
    BUTTON_RELEASE: "BUTTON_RELEASE",

    PLAYER_INPUT_ACCEPTED: "PLAYER_INPUT_ACCEPTED",
    PLAYER_INPUT_REJECTED: "PLAYER_INPUT_REJECTED",
    PLAYER_PRESS_LIMIT_REACHED: "PLAYER_PRESS_LIMIT_REACHED",
    PLAYER_COOLDOWN_STARTED: "PLAYER_COOLDOWN_STARTED",

    PHYSICS_STARTED: "PHYSICS_STARTED",
    PHYSICS_UPDATED: "PHYSICS_UPDATED",
    PHYSICS_BRAKING: "PHYSICS_BRAKING",
    PHYSICS_STOPPED: "PHYSICS_STOPPED",

    WINNER_DETERMINED: "WINNER_DETERMINED",

    WINNING_SECTOR_RESOLVED: "WINNING_SECTOR_RESOLVED",
    GAME_RESULT_READY: "GAME_RESULT_READY",
    GAME_RESULT_REMOVED: "GAME_RESULT_REMOVED",

    PAYMENT_STARTED: "PAYMENT_STARTED",
    PAYMENT_PREPARED: "PAYMENT_PREPARED",
    PAYMENT_COMPLETED: "PAYMENT_COMPLETED",
    PAYMENT_FAILED: "PAYMENT_FAILED",
    PAYMENT_REMOVED: "PAYMENT_REMOVED",

    RECOVERY_STARTED: "RECOVERY_STARTED",
    RECOVERY_SNAPSHOT_CREATED: "RECOVERY_SNAPSHOT_CREATED",
    PLAYER_RECOVERED: "PLAYER_RECOVERED",
    SESSION_RECOVERED: "SESSION_RECOVERED",
    RECOVERY_FAILED: "RECOVERY_FAILED",
    RECOVERY_REMOVED: "RECOVERY_REMOVED",

    AUDIT_STARTED: "AUDIT_STARTED",
    AUDIT_COMPLETED: "AUDIT_COMPLETED",
    AUDIT_FAILED: "AUDIT_FAILED",
    AUDIT_REPORT_CREATED: "AUDIT_REPORT_CREATED",
    AUDIT_REPORT_REMOVED: "AUDIT_REPORT_REMOVED",

    LOBBY_CREATE_ROOM_REQUEST: "LOBBY_CREATE_ROOM_REQUEST",
    LOBBY_JOIN_ROOM_REQUEST: "LOBBY_JOIN_ROOM_REQUEST",
    LOBBY_LEAVE_ROOM_REQUEST: "LOBBY_LEAVE_ROOM_REQUEST",
    LOBBY_SOCKET_DISCONNECTED: "LOBBY_SOCKET_DISCONNECTED",
    LOBBY_SOCKET_DELIVERY: "LOBBY_SOCKET_DELIVERY",

    SERVER_SHUTDOWN: "SERVER_SHUTDOWN"
});
