export const EVENT_SOURCES = Object.freeze({
    APPLICATION: "Application",
    SOCKET_GATEWAY: "SocketGateway",
    LOGGER_SERVICE: "LoggerService",

    GAME_MANAGER: "GameManager",
    ROOM_MANAGER: "RoomManager",
    PLAYER_MANAGER: "PlayerManager",

    CONFIGURATION_ENGINE: "ConfigurationEngine",
    GAME_STATE_ENGINE: "GameStateEngine",
    GAME_CLOCK_ENGINE: "GameClockEngine",
    PHYSICS_ENGINE: "PhysicsEngine",
    INPUT_AUTHORITY: "InputAuthority",
    WINNER_ENGINE: "WinnerEngine",
    PAYMENT_ENGINE: "PaymentEngine",
    RECOVERY_ENGINE: "RecoveryEngine",
    AUDIT_ENGINE: "AuditEngine",
    ROOM_LOBBY_BRIDGE: "RoomLobbyBridge",
    SIMULATION_LOOP: "SimulationLoop",
    GAME_STATE_ACTIVATION: "GameStateActivation",
    GAME_CLOCK_BROADCASTER: "GameClockBroadcaster",
    GAMEPLAY_LIFECYCLE: "GameplayLifecycle",
    GAMEPLAY_PHASE_LIFECYCLE: "GameplayPhaseLifecycle",
    READY_PHASE_BROADCASTER: "ReadyPhaseBroadcaster",
    SELF_TEST_PHASE_CONTROLLER: "SelfTestPhaseController",
    SPEED_PHASE_CONTROLLER: "SpeedPhaseController",
    SETUP_SESSION_LIFECYCLE: "SetupSessionLifecycle",
    OPERATIONAL_METRICS: "OperationalMetrics"
});
