export const EVENT_TYPES = Object.freeze({
    TEST_EVENT: "TEST_EVENT",

    CATALOG_LOADED: "CATALOG_LOADED",

    CONFIGURATION_READY: "CONFIGURATION_READY",
    CONFIGURATION_REMOVED: "CONFIGURATION_REMOVED",

    WHEEL_CONFIGURATION: "WHEEL_CONFIGURATION",

    GAME_CREATED: "GAME_CREATED",
    GAME_INITIALIZED: "GAME_INITIALIZED",
    GAME_STARTED: "GAME_STARTED",
    GAME_STATE_CHANGED: "GAME_STATE_CHANGED",
    GAME_STATE_REJECTED: "GAME_STATE_REJECTED",

    CLOCK_STARTED: "CLOCK_STARTED",
    CLOCK_PAUSED: "CLOCK_PAUSED",
    CLOCK_RESUMED: "CLOCK_RESUMED",
    CLOCK_STOPPED: "CLOCK_STOPPED",
    CLOCK_UPDATE: "CLOCK_UPDATE",
    PHASE_TIMEOUT: "PHASE_TIMEOUT",

    // P5.11 — Pre-game preparation (before READY).
    PRE_GAME_READY_STARTED: "PRE_GAME_READY_STARTED",
    PRE_GAME_READY_UPDATED: "PRE_GAME_READY_UPDATED",
    PRE_GAME_READY_COMPLETED: "PRE_GAME_READY_COMPLETED",
    PLAYER_READY_CONFIRM: "PLAYER_READY_CONFIRM",

    // P5.3 — Authoritative Page5 phase lifecycle (READY → … → RESULT).
    READY_STARTED: "READY_STARTED",
    READY_COMPLETED: "READY_COMPLETED",
    SELF_TEST_STARTED: "SELF_TEST_STARTED",
    SELF_TEST_COMPLETED: "SELF_TEST_COMPLETED",
    SPEED_STARTED: "SPEED_STARTED",
    SPEED_COMPLETED: "SPEED_COMPLETED",
    BRAKE_STARTED: "BRAKE_STARTED",
    BRAKE_COMPLETED: "BRAKE_COMPLETED",
    RESULT_STARTED: "RESULT_STARTED",
    RESULT_COMPLETED: "RESULT_COMPLETED",
    OPEN_PAGE6: "OPEN_PAGE6",

    // R6.5 — Page6 result linger expired; RoomLobbyBridge finishes the session.
    RESULT_SESSION_EXPIRED: "RESULT_SESSION_EXPIRED",
    // R6.5 — Authoritative signal that the completed session is fully closed.
    SESSION_FINISHED: "SESSION_FINISHED",

    // R12.5G — Untrusted client Page6 / InfoBar diagnostic metadata only.
    CLIENT_PAGE6_DIAGNOSTIC: "CLIENT_PAGE6_DIAGNOSTIC",

    GAME_FINISHED: "GAME_FINISHED",
    GAME_DESTROYED: "GAME_DESTROYED",

    CLEANUP_COMPLETED: "CLEANUP_COMPLETED",

    ROOM_CREATED: "ROOM_CREATED",
    ROOM_FULL: "ROOM_FULL",
    ROOM_LOCKED: "ROOM_LOCKED",
    ROOM_UNLOCKED: "ROOM_UNLOCKED",
    ROOM_DESTROYED: "ROOM_DESTROYED",

    // C5.6C — Setup Session (prep before Game Session). COMPLETED is internal
    // EventBus handoff to GameManager; STARTED / SYNC / EXPIRED are authoritative
    // protocol surfaces for clients.
    SETUP_SESSION_STARTED: "SETUP_SESSION_STARTED",
    SETUP_SESSION_SYNC: "SETUP_SESSION_SYNC",
    SETUP_SESSION_COMPLETED: "SETUP_SESSION_COMPLETED",
    SETUP_SESSION_EXPIRED: "SETUP_SESSION_EXPIRED",

    // R5.15 — All Page2 profiles stored in PlayerManager; wheel config may build.
    ALL_PLAYER_PROFILES_READY: "ALL_PLAYER_PROFILES_READY",

    // R1.1 — Entry payment finished; GameManager may activate gameplay.
    ENTRY_PAYMENT_COMPLETED: "ENTRY_PAYMENT_COMPLETED",

    PLAYER_JOINED: "PLAYER_JOINED",
    PLAYER_LEFT: "PLAYER_LEFT",
    PLAYER_CREATED: "PLAYER_CREATED",
    PLAYER_CONNECTED: "PLAYER_CONNECTED",
    PLAYER_DISCONNECTED: "PLAYER_DISCONNECTED",
    PLAYER_RUNTIME_UPDATED: "PLAYER_RUNTIME_UPDATED",
    PLAYER_REMOVED: "PLAYER_REMOVED",

    BUTTON_PRESS: "BUTTON_PRESS",
    BUTTON_RELEASE: "BUTTON_RELEASE",

    PLAYER_INPUT_ACCEPTED: "PLAYER_INPUT_ACCEPTED",
    PLAYER_INPUT_REJECTED: "PLAYER_INPUT_REJECTED",
    PLAYER_PRESS_LIMIT_REACHED: "PLAYER_PRESS_LIMIT_REACHED",
    PLAYER_COOLDOWN_STARTED: "PLAYER_COOLDOWN_STARTED",

    PHYSICS_STARTED: "PHYSICS_STARTED",
    PHYSICS_UPDATED: "PHYSICS_UPDATED",
    PHYSICS_BRAKING: "PHYSICS_BRAKING",
    PHYSICS_STOPPED: "PHYSICS_STOPPED",

    WINNER_DETERMINED: "WINNER_DETERMINED",
    WINNER_RESOLUTION_FAILED: "WINNER_RESOLUTION_FAILED",

    WINNING_SECTOR_RESOLVED: "WINNING_SECTOR_RESOLVED",
    GAME_RESULT_READY: "GAME_RESULT_READY",
    GAME_RESULT_REMOVED: "GAME_RESULT_REMOVED",

    PAYMENT_STARTED: "PAYMENT_STARTED",
    PAYMENT_PREPARED: "PAYMENT_PREPARED",
    PAYMENT_COMPLETED: "PAYMENT_COMPLETED",
    PAYMENT_FAILED: "PAYMENT_FAILED",
    PAYMENT_REMOVED: "PAYMENT_REMOVED",

    RECOVERY_STARTED: "RECOVERY_STARTED",
    RECOVERY_SNAPSHOT_CREATED: "RECOVERY_SNAPSHOT_CREATED",
    PLAYER_RECOVERED: "PLAYER_RECOVERED",
    SESSION_RECOVERED: "SESSION_RECOVERED",
    RECOVERY_FAILED: "RECOVERY_FAILED",
    RECOVERY_REMOVED: "RECOVERY_REMOVED",

    AUDIT_STARTED: "AUDIT_STARTED",
    AUDIT_COMPLETED: "AUDIT_COMPLETED",
    AUDIT_FAILED: "AUDIT_FAILED",
    AUDIT_READY: "AUDIT_READY",
    AUDIT_REPORT_CREATED: "AUDIT_REPORT_CREATED",
    AUDIT_REPORT_REMOVED: "AUDIT_REPORT_REMOVED",

    LOBBY_CREATE_ROOM_REQUEST: "LOBBY_CREATE_ROOM_REQUEST",
    LOBBY_JOIN_ROOM_REQUEST: "LOBBY_JOIN_ROOM_REQUEST",
    LOBBY_LEAVE_ROOM_REQUEST: "LOBBY_LEAVE_ROOM_REQUEST",
    LOBBY_UPDATE_PLAYER_PROFILE_REQUEST: "LOBBY_UPDATE_PLAYER_PROFILE_REQUEST",
    LOBBY_SUBMIT_SECRET_MATRIX_REQUEST: "LOBBY_SUBMIT_SECRET_MATRIX_REQUEST",
    LOBBY_CONFIRM_VERIFY_REQUEST: "LOBBY_CONFIRM_VERIFY_REQUEST",
    LOBBY_VERIFY_NEXT_REQUEST: "LOBBY_VERIFY_NEXT_REQUEST",
    LOBBY_DEBUG_START_GAME_REQUEST: "LOBBY_DEBUG_START_GAME_REQUEST",
    LOBBY_WALLET_CONNECT_STARTED_REQUEST: "LOBBY_WALLET_CONNECT_STARTED_REQUEST",
    LOBBY_WALLET_CONNECT_REPORT_REQUEST: "LOBBY_WALLET_CONNECT_REPORT_REQUEST",
    LOBBY_WALLET_DISCONNECT_REPORT_REQUEST: "LOBBY_WALLET_DISCONNECT_REPORT_REQUEST",
    LOBBY_TONCONNECT_AUTOPSY_SNAPSHOT_REQUEST:
        "LOBBY_TONCONNECT_AUTOPSY_SNAPSHOT_REQUEST",

    // T2.6 — WalletManager domain lifecycle events.
    WALLET_SESSION_CREATED: "WALLET_SESSION_CREATED",
    WALLET_CONNECTED: "WALLET_CONNECTED",
    WALLET_VERIFICATION_STARTED: "WALLET_VERIFICATION_STARTED",
    WALLET_VERIFIED: "WALLET_VERIFIED",
    WALLET_DISCONNECTED: "WALLET_DISCONNECTED",
    WALLET_EXPIRED: "WALLET_EXPIRED",
    WALLET_REVOKED: "WALLET_REVOKED",
    WALLET_CHANGED: "WALLET_CHANGED",
    LOBBY_SOCKET_DISCONNECTED: "LOBBY_SOCKET_DISCONNECTED",
    LOBBY_SOCKET_DELIVERY: "LOBBY_SOCKET_DELIVERY",

    // P6.2 — all seats connected with matching session wallets.
    PAYMENT_CONNECTION_READY: "PAYMENT_CONNECTION_READY",

    // P6.3 — authoritative entry Payment Session (no chain / no Smart Contract).
    PAYMENT_SESSION_CREATED: "PAYMENT_SESSION_CREATED",
    PAYMENT_SESSION_UPDATED: "PAYMENT_SESSION_UPDATED",
    PAYMENT_REQUEST: "PAYMENT_REQUEST",
    PAYMENT_SESSION_COMPLETED: "PAYMENT_SESSION_COMPLETED",
    PAYMENT_SESSION_FAILED: "PAYMENT_SESSION_FAILED",

    // T2.7 — PaymentSessionManager domain lifecycle events.
    PAYMENT_RECEIVED: "PAYMENT_RECEIVED",
    PAYMENT_CONFIRMED: "PAYMENT_CONFIRMED",
    PAYMENT_REJECTED: "PAYMENT_REJECTED",
    PAYMENT_TIMEOUT: "PAYMENT_TIMEOUT",
    PAYMENT_SESSION_RECOVERED: "PAYMENT_SESSION_RECOVERED",
    LOBBY_PAYMENT_CONFIRM_INTENT_REQUEST: "LOBBY_PAYMENT_CONFIRM_INTENT_REQUEST",
    LOBBY_PAYMENT_CANCEL_INTENT_REQUEST: "LOBBY_PAYMENT_CANCEL_INTENT_REQUEST",

    // P6.6 — BlockchainMonitor → PaymentSessionManager.
    PAYMENT_BLOCKCHAIN_CONFIRMED: "PAYMENT_BLOCKCHAIN_CONFIRMED",
    PAYMENT_BLOCKCHAIN_REJECTED: "PAYMENT_BLOCKCHAIN_REJECTED",

    // T2.5 — BlockchainMonitor observation facts (not business decisions).
    BLOCKCHAIN_CONNECTED: "BLOCKCHAIN_CONNECTED",
    BLOCKCHAIN_DISCONNECTED: "BLOCKCHAIN_DISCONNECTED",
    CONTRACT_DEPLOYMENT_CONFIRMED: "CONTRACT_DEPLOYMENT_CONFIRMED",
    CONTRACT_DEPLOYMENT_FAILED: "CONTRACT_DEPLOYMENT_FAILED",
    PAYMENT_TRANSACTION_DETECTED: "PAYMENT_TRANSACTION_DETECTED",
    PAYMENT_TRANSACTION_CONFIRMED: "PAYMENT_TRANSACTION_CONFIRMED",
    SETTLEMENT_TRANSACTION_CONFIRMED: "SETTLEMENT_TRANSACTION_CONFIRMED",
    // R7.66G — GameEscrow winner/owner payout proofs verified on escrow.
    GAME_ESCROW_SETTLEMENT_VERIFIED: "GAME_ESCROW_SETTLEMENT_VERIFIED",
    GAME_ESCROW_SETTLEMENT_REJECTED: "GAME_ESCROW_SETTLEMENT_REJECTED",
    // R7.69A — GameEscrow player STAKE confirmed on-chain.
    GAME_ESCROW_STAKE_CONFIRMED: "GAME_ESCROW_STAKE_CONFIRMED",
    GAME_ESCROW_STAKE_REJECTED: "GAME_ESCROW_STAKE_REJECTED",
    // R7.69C — GameEscrow EMERGENCY_CANCEL refund confirmed on-chain.
    GAME_ESCROW_REFUND_CONFIRMED: "GAME_ESCROW_REFUND_CONFIRMED",
    GAME_ESCROW_REFUND_REJECTED: "GAME_ESCROW_REFUND_REJECTED",
    GAME_ESCROW_CANCEL_CONFIRMED: "GAME_ESCROW_CANCEL_CONFIRMED",
    // R17.8O.1 — Partial payment escrow unwind observability.
    ESCROW_CANCEL_REQUESTED: "ESCROW_CANCEL_REQUESTED",
    ESCROW_CANCEL_CONFIRMED: "ESCROW_CANCEL_CONFIRMED",
    ESCROW_CANCEL_FAILED: "ESCROW_CANCEL_FAILED",
    ESCROW_REFUND_PENDING: "ESCROW_REFUND_PENDING",
    ESCROW_REFUND_CONFIRMED: "ESCROW_REFUND_CONFIRMED",
    TRANSACTION_FAILED: "TRANSACTION_FAILED",
    BLOCKCHAIN_CONTRACT_STATE_CHANGED: "BLOCKCHAIN_CONTRACT_STATE_CHANGED",

    // P6.4 — Game Smart Contract architecture (no chain deploy).
    GAME_CONTRACT_UPDATED: "GAME_CONTRACT_UPDATED",

    // P6.5 — deployment + payment-request handoff.
    GAME_CONTRACT_DEPLOYED: "GAME_CONTRACT_DEPLOYED",
    GAME_CONTRACT_DEPLOY_FAILED: "GAME_CONTRACT_DEPLOY_FAILED",
    GAME_CONTRACT_READY_FOR_PAYMENTS: "GAME_CONTRACT_READY_FOR_PAYMENTS",

    // R17.8V.2P.J — post-persist deployment cost capture (no chain lookup yet).
    DEPLOYMENT_COST_CAPTURE_REQUESTED: "DEPLOYMENT_COST_CAPTURE_REQUESTED",

    // R17.8V.2P.S — snapshot freeze notification for deferred reimbursement create.
    DEPLOYMENT_COST_SNAPSHOT_FROZEN: "DEPLOYMENT_COST_SNAPSHOT_FROZEN",

    // R17.8V.2P.N — reimbursement queue audit (no TON transfer).
    DEPLOYMENT_REIMBURSEMENT_CREATED: "DEPLOYMENT_REIMBURSEMENT_CREATED",
    DEPLOYMENT_REIMBURSEMENT_SKIPPED: "DEPLOYMENT_REIMBURSEMENT_SKIPPED",
    DEPLOYMENT_REIMBURSEMENT_NO_SNAPSHOT: "DEPLOYMENT_REIMBURSEMENT_NO_SNAPSHOT",
    DEPLOYMENT_REIMBURSEMENT_DEPLOY_WALLET_MISMATCH:
        "DEPLOYMENT_REIMBURSEMENT_DEPLOY_WALLET_MISMATCH",

    // R17.8V.2P.P — reimbursement confirmation audit (chain lookup only).
    REIMBURSEMENT_CONFIRMATION_STARTED: "REIMBURSEMENT_CONFIRMATION_STARTED",
    REIMBURSEMENT_CONFIRMED: "REIMBURSEMENT_CONFIRMED",
    REIMBURSEMENT_CONFIRMATION_FAILED: "REIMBURSEMENT_CONFIRMATION_FAILED",
    REIMBURSEMENT_CONFIRMATION_RETRY: "REIMBURSEMENT_CONFIRMATION_RETRY",

    // R17.8V.2P.Q — production safety audits.
    REIMBURSEMENT_POLICY_BLOCKED: "REIMBURSEMENT_POLICY_BLOCKED",
    REIMBURSEMENT_LOW_BALANCE: "REIMBURSEMENT_LOW_BALANCE",
    REIMBURSEMENT_DAILY_LIMIT_REACHED: "REIMBURSEMENT_DAILY_LIMIT_REACHED",
    REIMBURSEMENT_TX_RECOVERED: "REIMBURSEMENT_TX_RECOVERED",

    // P6.7 — contract payments fully confirmed on-chain.
    GAME_CONTRACT_PAYMENTS_COMPLETE: "GAME_CONTRACT_PAYMENTS_COMPLETE",

    // T2.4 — GameContractManager domain lifecycle events.
    CONTRACT_CREATED: "CONTRACT_CREATED",
    CONTRACT_DEPLOYING: "CONTRACT_DEPLOYING",
    CONTRACT_DEPLOYED: "CONTRACT_DEPLOYED",
    CONTRACT_STATE_CHANGED: "CONTRACT_STATE_CHANGED",
    CONTRACT_READY: "CONTRACT_READY",
    CONTRACT_FAILED: "CONTRACT_FAILED",
    CONTRACT_ARCHIVED: "CONTRACT_ARCHIVED",

    // P6.7 — authoritative gameplay start gate (after PAYMENTS_COMPLETE).
    GAME_START_AUTHORIZED: "GAME_START_AUTHORIZED",
    GAME_INITIALIZING: "GAME_INITIALIZING",
    GAME_START_BOOTSTRAP_READY: "GAME_START_BOOTSTRAP_READY",
    GAME_START_FAILED: "GAME_START_FAILED",

    // P6.8B — post-winner TON contract settlement (server-authoritative).
    SETTLEMENT_STARTED: "SETTLEMENT_STARTED",
    SETTLEMENT_SUBMITTED: "SETTLEMENT_SUBMITTED",
    SETTLEMENT_CONFIRMED: "SETTLEMENT_CONFIRMED",
    SETTLEMENT_COMPLETED: "SETTLEMENT_COMPLETED",
    SETTLEMENT_FAILED: "SETTLEMENT_FAILED",

    // T2.8 — ContractSettlementManager domain lifecycle events.
    SETTLEMENT_SESSION_CREATED: "SETTLEMENT_SESSION_CREATED",
    SETTLEMENT_PENDING: "SETTLEMENT_PENDING",
    SETTLEMENT_TIMEOUT: "SETTLEMENT_TIMEOUT",
    SETTLEMENT_RECOVERED: "SETTLEMENT_RECOVERED",

    // T2.9 — TonFinancialRecovery coordinator lifecycle events.
    FINANCIAL_RECOVERY_STARTED: "FINANCIAL_RECOVERY_STARTED",
    FINANCIAL_RECOVERY_PROGRESS: "FINANCIAL_RECOVERY_PROGRESS",
    FINANCIAL_RECOVERY_VALIDATION_STARTED: "FINANCIAL_RECOVERY_VALIDATION_STARTED",
    FINANCIAL_RECOVERY_COMPLETED: "FINANCIAL_RECOVERY_COMPLETED",
    FINANCIAL_RECOVERY_FAILED: "FINANCIAL_RECOVERY_FAILED",

    // R14.4 — Advertisement scheduler (isolated from gameplay / payments / rooms).
    ADVERTISEMENT_CHANGED: "ADVERTISEMENT_CHANGED",
    ADVERTISEMENT_SYNC_REQUEST: "ADVERTISEMENT_SYNC_REQUEST",
    ADVERTISEMENT_SYNC_RESPONSE: "ADVERTISEMENT_SYNC_RESPONSE",

    // R17.9G.1 — Developer Console runtime configuration mutation audit.
    RUNTIME_CONFIG_CHANGED: "RUNTIME_CONFIG_CHANGED",

    // R17.9I.3 — Developer Console audio registry mutation audit.
    AUDIO_REGISTRY_CHANGED: "AUDIO_REGISTRY_CHANGED",

    SERVER_SHUTDOWN: "SERVER_SHUTDOWN"
});
