export const EVENT_SOURCES = Object.freeze({
    APPLICATION: "Application",
    SOCKET_GATEWAY: "SocketGateway",
    LOGGER_SERVICE: "LoggerService",

    GAME_MANAGER: "GameManager",
    ROOM_MANAGER: "RoomManager",
    PLAYER_MANAGER: "PlayerManager",

    CONFIGURATION_ENGINE: "ConfigurationEngine",
    GAME_STATE_ENGINE: "GameStateEngine",
    GAME_CLOCK_ENGINE: "GameClockEngine",
    PHYSICS_ENGINE: "PhysicsEngine",
    INPUT_AUTHORITY: "InputAuthority",
    WINNER_ENGINE: "WinnerEngine",
    PAYMENT_ENGINE: "PaymentEngine",
    RECOVERY_ENGINE: "RecoveryEngine",
    AUDIT_ENGINE: "AuditEngine",
    ROOM_LOBBY_BRIDGE: "RoomLobbyBridge",
    SIMULATION_LOOP: "SimulationLoop",
    GAME_STATE_ACTIVATION: "GameStateActivation",
    GAME_CLOCK_BROADCASTER: "GameClockBroadcaster",
    GAMEPLAY_LIFECYCLE: "GameplayLifecycle",
    GAMEPLAY_PHASE_LIFECYCLE: "GameplayPhaseLifecycle",
    READY_PHASE_BROADCASTER: "ReadyPhaseBroadcaster",
    PRE_GAME_READY_ACTIVATION: "PreGameReadyActivation",
    SELF_TEST_PHASE_CONTROLLER: "SelfTestPhaseController",
    SPEED_PHASE_CONTROLLER: "SpeedPhaseController",
    BRAKE_PHASE_CONTROLLER: "BrakePhaseController",
    RESULT_ACTIVATION: "ResultActivation",
    SETUP_SESSION_LIFECYCLE: "SetupSessionLifecycle",
    RESULT_SESSION_LIFECYCLE: "ResultSessionLifecycle",
    PAYMENT_SESSION_MANAGER: "PaymentSessionManager",
    GAME_CONTRACT_MANAGER: "GameContractManager",
    BLOCKCHAIN_MONITOR: "BlockchainMonitor",
    GAME_START_AUTHORIZATION: "GameStartAuthorization",
    CONTRACT_SETTLEMENT_MANAGER: "ContractSettlementManager",
    WALLET_MANAGER: "WalletManager",
    TON_FINANCIAL_RECOVERY: "TonFinancialRecovery",
    OPERATIONAL_METRICS: "OperationalMetrics"
});
