export const EVENT_TYPES = Object.freeze({
    TEST_EVENT: "TEST_EVENT",

    CATALOG_LOADED: "CATALOG_LOADED",

    CONFIGURATION_READY: "CONFIGURATION_READY",
    CONFIGURATION_REMOVED: "CONFIGURATION_REMOVED",

    GAME_CREATED: "GAME_CREATED",
    GAME_INITIALIZED: "GAME_INITIALIZED",
    GAME_STARTED: "GAME_STARTED",
    GAME_STATE_CHANGED: "GAME_STATE_CHANGED",
    GAME_STATE_REJECTED: "GAME_STATE_REJECTED",

    CLOCK_STARTED: "CLOCK_STARTED",
    CLOCK_PAUSED: "CLOCK_PAUSED",
    CLOCK_RESUMED: "CLOCK_RESUMED",
    CLOCK_STOPPED: "CLOCK_STOPPED",
    CLOCK_UPDATE: "CLOCK_UPDATE",
    PHASE_TIMEOUT: "PHASE_TIMEOUT",

    // P5.3 — Authoritative Page5 phase lifecycle (READY → … → RESULT).
    READY_STARTED: "READY_STARTED",
    READY_COMPLETED: "READY_COMPLETED",
    SELF_TEST_STARTED: "SELF_TEST_STARTED",
    SELF_TEST_COMPLETED: "SELF_TEST_COMPLETED",
    SPEED_STARTED: "SPEED_STARTED",
    SPEED_COMPLETED: "SPEED_COMPLETED",
    BRAKE_STARTED: "BRAKE_STARTED",
    BRAKE_COMPLETED: "BRAKE_COMPLETED",
    RESULT_STARTED: "RESULT_STARTED",
    RESULT_COMPLETED: "RESULT_COMPLETED",
    OPEN_PAGE6: "OPEN_PAGE6",

    GAME_FINISHED: "GAME_FINISHED",
    GAME_DESTROYED: "GAME_DESTROYED",

    CLEANUP_COMPLETED: "CLEANUP_COMPLETED",

    ROOM_CREATED: "ROOM_CREATED",
    ROOM_FULL: "ROOM_FULL",
    ROOM_LOCKED: "ROOM_LOCKED",
    ROOM_DESTROYED: "ROOM_DESTROYED",

    // C5.6C — Setup Session (prep before Game Session). COMPLETED is internal
    // EventBus handoff to GameManager; STARTED / SYNC / EXPIRED are authoritative
    // protocol surfaces for clients.
    SETUP_SESSION_STARTED: "SETUP_SESSION_STARTED",
    SETUP_SESSION_SYNC: "SETUP_SESSION_SYNC",
    SETUP_SESSION_COMPLETED: "SETUP_SESSION_COMPLETED",
    SETUP_SESSION_EXPIRED: "SETUP_SESSION_EXPIRED",

    // R1.1 — Entry payment finished; GameManager may activate gameplay.
    ENTRY_PAYMENT_COMPLETED: "ENTRY_PAYMENT_COMPLETED",

    PLAYER_JOINED: "PLAYER_JOINED",
    PLAYER_LEFT: "PLAYER_LEFT",
    PLAYER_CREATED: "PLAYER_CREATED",
    PLAYER_CONNECTED: "PLAYER_CONNECTED",
    PLAYER_DISCONNECTED: "PLAYER_DISCONNECTED",
    PLAYER_RUNTIME_UPDATED: "PLAYER_RUNTIME_UPDATED",
    PLAYER_REMOVED: "PLAYER_REMOVED",

    BUTTON_PRESS: "BUTTON_PRESS",
    BUTTON_RELEASE: "BUTTON_RELEASE",

    PLAYER_INPUT_ACCEPTED: "PLAYER_INPUT_ACCEPTED",
    PLAYER_INPUT_REJECTED: "PLAYER_INPUT_REJECTED",
    PLAYER_PRESS_LIMIT_REACHED: "PLAYER_PRESS_LIMIT_REACHED",
    PLAYER_COOLDOWN_STARTED: "PLAYER_COOLDOWN_STARTED",

    PHYSICS_STARTED: "PHYSICS_STARTED",
    PHYSICS_UPDATED: "PHYSICS_UPDATED",
    PHYSICS_BRAKING: "PHYSICS_BRAKING",
    PHYSICS_STOPPED: "PHYSICS_STOPPED",

    WINNER_DETERMINED: "WINNER_DETERMINED",

    WINNING_SECTOR_RESOLVED: "WINNING_SECTOR_RESOLVED",
    GAME_RESULT_READY: "GAME_RESULT_READY",
    GAME_RESULT_REMOVED: "GAME_RESULT_REMOVED",

    PAYMENT_STARTED: "PAYMENT_STARTED",
    PAYMENT_PREPARED: "PAYMENT_PREPARED",
    PAYMENT_COMPLETED: "PAYMENT_COMPLETED",
    PAYMENT_FAILED: "PAYMENT_FAILED",
    PAYMENT_REMOVED: "PAYMENT_REMOVED",

    RECOVERY_STARTED: "RECOVERY_STARTED",
    RECOVERY_SNAPSHOT_CREATED: "RECOVERY_SNAPSHOT_CREATED",
    PLAYER_RECOVERED: "PLAYER_RECOVERED",
    SESSION_RECOVERED: "SESSION_RECOVERED",
    RECOVERY_FAILED: "RECOVERY_FAILED",
    RECOVERY_REMOVED: "RECOVERY_REMOVED",

    AUDIT_STARTED: "AUDIT_STARTED",
    AUDIT_COMPLETED: "AUDIT_COMPLETED",
    AUDIT_FAILED: "AUDIT_FAILED",
    AUDIT_READY: "AUDIT_READY",
    AUDIT_REPORT_CREATED: "AUDIT_REPORT_CREATED",
    AUDIT_REPORT_REMOVED: "AUDIT_REPORT_REMOVED",

    LOBBY_CREATE_ROOM_REQUEST: "LOBBY_CREATE_ROOM_REQUEST",
    LOBBY_JOIN_ROOM_REQUEST: "LOBBY_JOIN_ROOM_REQUEST",
    LOBBY_LEAVE_ROOM_REQUEST: "LOBBY_LEAVE_ROOM_REQUEST",
    LOBBY_UPDATE_PLAYER_PROFILE_REQUEST: "LOBBY_UPDATE_PLAYER_PROFILE_REQUEST",
    LOBBY_SUBMIT_SECRET_MATRIX_REQUEST: "LOBBY_SUBMIT_SECRET_MATRIX_REQUEST",
    LOBBY_CONFIRM_VERIFY_REQUEST: "LOBBY_CONFIRM_VERIFY_REQUEST",
    LOBBY_VERIFY_NEXT_REQUEST: "LOBBY_VERIFY_NEXT_REQUEST",
    LOBBY_DEBUG_START_GAME_REQUEST: "LOBBY_DEBUG_START_GAME_REQUEST",
    LOBBY_SOCKET_DISCONNECTED: "LOBBY_SOCKET_DISCONNECTED",
    LOBBY_SOCKET_DELIVERY: "LOBBY_SOCKET_DELIVERY",

    SERVER_SHUTDOWN: "SERVER_SHUTDOWN"
});
