/**
 * R8.0B — Release notes markdown generator.
 */

export class ReleaseNotesGenerator {

    /**
     * @param {{
     *   version: string,
     *   channel: string,
     *   commit: string,
     *   builtAt: string,
     *   fingerprint: string,
     *   validationStatus?: string,
     *   summary?: string,
     *   completedStages?: string[],
     *   knownLimitations?: string[],
     *   breakingChanges?: string[],
     *   compatibility?: object
     * }} input
     */
    static generate(input) {

        const stages = input.completedStages ?? [
            "Server Authoritative Gameplay",
            "Production Infrastructure (R7)",
            "Production Validation Suite (R7.0H)",
            "Release Candidate Architecture (R8.0A)",
            "Release Build System (R8.0B)"
        ];

        const limitations = input.knownLimitations ?? [
            "Gameplay and infrastructure remain frozen; this package is a release artifact set.",
            "Client artifact may be a source snapshot if a production client bundle was not present at build time."
        ];

        const breaking = input.breakingChanges ?? [
            "None for this release train (authority contracts unchanged)."
        ];

        const compat = input.compatibility ?? {
            node: ">=18",
            serverAuthoritative: true
        };

        const lines = [
            `# WheelWin ${input.version}`,
            "",
            `**Channel:** ${input.channel}`,
            `**Built (UTC):** ${input.builtAt}`,
            `**Commit:** ${input.commit}`,
            `**Fingerprint:** \`${input.fingerprint}\``,
            `**Validation:** ${input.validationStatus ?? "see attached reports"}`,
            "",
            "## Summary",
            "",
            input.summary
                ?? "Release Candidate / release package generated by the R8.0B Release Build System.",
            "",
            "## Completed stages",
            ""
        ];

        for (const stage of stages) {

            lines.push(`- ${stage}`);

        }

        lines.push("", "## Known limitations", "");

        for (const item of limitations) {

            lines.push(`- ${item}`);

        }

        lines.push("", "## Breaking changes", "");

        for (const item of breaking) {

            lines.push(`- ${item}`);

        }

        lines.push(
            "",
            "## Compatibility",
            "",
            "```json",
            JSON.stringify(compat, null, 2),
            "```",
            "",
            "## Validation status",
            "",
            input.validationStatus ?? "Run `npm run validate:production` on the tagged commit.",
            ""
        );

        return lines.join("\n");

    }

}
