/**
 * T2.6 — Wallet session lifecycle states and transitions.
 */

export const WALLET_SESSION_STATUS = Object.freeze({
    CREATED: "CREATED",
    CONNECTED: "CONNECTED",
    VERIFICATION_PENDING: "VERIFICATION_PENDING",
    VERIFIED: "VERIFIED",
    DISCONNECTED: "DISCONNECTED",
    EXPIRED: "EXPIRED",
    INVALID: "INVALID",
    REVOKED: "REVOKED"
});

export const WALLET_SESSION_TRANSITIONS = Object.freeze({
    [WALLET_SESSION_STATUS.CREATED]: Object.freeze([
        WALLET_SESSION_STATUS.CONNECTED,
        WALLET_SESSION_STATUS.INVALID,
        WALLET_SESSION_STATUS.EXPIRED,
        WALLET_SESSION_STATUS.REVOKED
    ]),
    [WALLET_SESSION_STATUS.CONNECTED]: Object.freeze([
        WALLET_SESSION_STATUS.VERIFICATION_PENDING,
        WALLET_SESSION_STATUS.VERIFIED,
        WALLET_SESSION_STATUS.DISCONNECTED,
        WALLET_SESSION_STATUS.EXPIRED,
        WALLET_SESSION_STATUS.INVALID,
        WALLET_SESSION_STATUS.REVOKED
    ]),
    [WALLET_SESSION_STATUS.VERIFICATION_PENDING]: Object.freeze([
        WALLET_SESSION_STATUS.VERIFIED,
        WALLET_SESSION_STATUS.INVALID,
        WALLET_SESSION_STATUS.DISCONNECTED,
        WALLET_SESSION_STATUS.EXPIRED,
        WALLET_SESSION_STATUS.REVOKED
    ]),
    [WALLET_SESSION_STATUS.VERIFIED]: Object.freeze([
        WALLET_SESSION_STATUS.DISCONNECTED,
        WALLET_SESSION_STATUS.EXPIRED,
        WALLET_SESSION_STATUS.REVOKED
    ]),
    [WALLET_SESSION_STATUS.DISCONNECTED]: Object.freeze([
        WALLET_SESSION_STATUS.CONNECTED,
        WALLET_SESSION_STATUS.EXPIRED,
        WALLET_SESSION_STATUS.REVOKED
    ]),
    [WALLET_SESSION_STATUS.EXPIRED]: Object.freeze([]),
    [WALLET_SESSION_STATUS.INVALID]: Object.freeze([
        WALLET_SESSION_STATUS.REVOKED
    ]),
    [WALLET_SESSION_STATUS.REVOKED]: Object.freeze([])
});

export const TERMINAL_WALLET_SESSION_STATUSES = Object.freeze([
    WALLET_SESSION_STATUS.EXPIRED,
    WALLET_SESSION_STATUS.REVOKED
]);

export function canTransitionWalletStatus(fromStatus, toStatus) {

    const allowed = WALLET_SESSION_TRANSITIONS[fromStatus] ?? [];

    return allowed.includes(toStatus);

}
