/**
 * R17.8V.2P.I — Deployment cost snapshot service result codes.
 */

export const DEPLOYMENT_COST_SERVICE_RESULT = Object.freeze({
    OK: "OK",
    FEATURE_DISABLED: "FEATURE_DISABLED",
    INVALID_CAPTURE_PAYLOAD: "INVALID_CAPTURE_PAYLOAD",
    SNAPSHOT_DUPLICATE: "SNAPSHOT_DUPLICATE",
    SNAPSHOT_CREATION_FAILED: "SNAPSHOT_CREATION_FAILED",
    NOT_INITIALIZED: "NOT_INITIALIZED"
});
