/**
 * R17.8V.2P.M — Deployment reimbursement service result codes.
 */

export const DEPLOYMENT_REIMBURSEMENT_SERVICE_RESULT = Object.freeze({
    OK: "OK",
    FEATURE_DISABLED: "FEATURE_DISABLED",
    INVALID_SNAPSHOT: "INVALID_SNAPSHOT",
    SNAPSHOT_NOT_FROZEN: "SNAPSHOT_NOT_FROZEN",
    NO_SNAPSHOT: "NO_SNAPSHOT",
    SKIPPED: "SKIPPED",
    INVALID_PAYLOAD: "INVALID_PAYLOAD",
    MISSING_REIMBURSEMENT_WALLET: "MISSING_REIMBURSEMENT_WALLET",
    DUPLICATE: "DUPLICATE",
    CREATE_FAILED: "CREATE_FAILED",
    NOT_INITIALIZED: "NOT_INITIALIZED",
    NOT_IMPLEMENTED: "NOT_IMPLEMENTED",
    SENT: "SENT",
    FAILED: "FAILED"
});
