/**
 * T2.8 — Settlement session lifecycle states and transitions.
 */

export const SETTLEMENT_SESSION_STATUS = Object.freeze({
    CREATED: "CREATED",
    PREPARING: "PREPARING",
    READY: "READY",
    SETTLEMENT_PENDING: "SETTLEMENT_PENDING",
    // R7.66G — GameEscrow waiting for winner/owner payout proofs.
    SETTLEMENT_PENDING_CONFIRMATION: "SETTLEMENT_PENDING_CONFIRMATION",
    SETTLEMENT_CONFIRMED: "SETTLEMENT_CONFIRMED",
    SETTLEMENT_COMPLETED: "SETTLEMENT_COMPLETED",
    SETTLEMENT_FAILED: "SETTLEMENT_FAILED",
    SETTLEMENT_TIMEOUT: "SETTLEMENT_TIMEOUT",
    RECOVERED: "RECOVERED"
});

export const SETTLEMENT_SESSION_TRANSITIONS = Object.freeze({
    [SETTLEMENT_SESSION_STATUS.CREATED]: Object.freeze([
        SETTLEMENT_SESSION_STATUS.PREPARING,
        SETTLEMENT_SESSION_STATUS.SETTLEMENT_FAILED
    ]),
    [SETTLEMENT_SESSION_STATUS.PREPARING]: Object.freeze([
        SETTLEMENT_SESSION_STATUS.READY,
        SETTLEMENT_SESSION_STATUS.SETTLEMENT_FAILED
    ]),
    [SETTLEMENT_SESSION_STATUS.READY]: Object.freeze([
        SETTLEMENT_SESSION_STATUS.SETTLEMENT_PENDING,
        SETTLEMENT_SESSION_STATUS.SETTLEMENT_PENDING_CONFIRMATION,
        SETTLEMENT_SESSION_STATUS.SETTLEMENT_FAILED
    ]),
    [SETTLEMENT_SESSION_STATUS.SETTLEMENT_PENDING]: Object.freeze([
        SETTLEMENT_SESSION_STATUS.SETTLEMENT_PENDING_CONFIRMATION,
        SETTLEMENT_SESSION_STATUS.SETTLEMENT_CONFIRMED,
        SETTLEMENT_SESSION_STATUS.SETTLEMENT_FAILED,
        SETTLEMENT_SESSION_STATUS.SETTLEMENT_TIMEOUT
    ]),
    [SETTLEMENT_SESSION_STATUS.SETTLEMENT_PENDING_CONFIRMATION]: Object.freeze([
        SETTLEMENT_SESSION_STATUS.SETTLEMENT_CONFIRMED,
        SETTLEMENT_SESSION_STATUS.SETTLEMENT_COMPLETED,
        SETTLEMENT_SESSION_STATUS.SETTLEMENT_FAILED,
        SETTLEMENT_SESSION_STATUS.SETTLEMENT_TIMEOUT
    ]),
    [SETTLEMENT_SESSION_STATUS.SETTLEMENT_CONFIRMED]: Object.freeze([
        SETTLEMENT_SESSION_STATUS.SETTLEMENT_COMPLETED
    ]),
    [SETTLEMENT_SESSION_STATUS.RECOVERED]: Object.freeze([
        SETTLEMENT_SESSION_STATUS.SETTLEMENT_PENDING,
        SETTLEMENT_SESSION_STATUS.SETTLEMENT_PENDING_CONFIRMATION,
        SETTLEMENT_SESSION_STATUS.SETTLEMENT_CONFIRMED,
        SETTLEMENT_SESSION_STATUS.SETTLEMENT_FAILED,
        SETTLEMENT_SESSION_STATUS.SETTLEMENT_TIMEOUT
    ]),
    [SETTLEMENT_SESSION_STATUS.SETTLEMENT_COMPLETED]: Object.freeze([]),
    [SETTLEMENT_SESSION_STATUS.SETTLEMENT_FAILED]: Object.freeze([
        SETTLEMENT_SESSION_STATUS.SETTLEMENT_COMPLETED
    ]),
    [SETTLEMENT_SESSION_STATUS.SETTLEMENT_TIMEOUT]: Object.freeze([])
});

export const TERMINAL_SETTLEMENT_SESSION_STATUSES = Object.freeze([
    SETTLEMENT_SESSION_STATUS.SETTLEMENT_COMPLETED,
    SETTLEMENT_SESSION_STATUS.SETTLEMENT_FAILED,
    SETTLEMENT_SESSION_STATUS.SETTLEMENT_TIMEOUT
]);

export const IN_PROGRESS_SETTLEMENT_SESSION_STATUSES = Object.freeze([
    SETTLEMENT_SESSION_STATUS.CREATED,
    SETTLEMENT_SESSION_STATUS.PREPARING,
    SETTLEMENT_SESSION_STATUS.READY,
    SETTLEMENT_SESSION_STATUS.SETTLEMENT_PENDING,
    SETTLEMENT_SESSION_STATUS.SETTLEMENT_PENDING_CONFIRMATION,
    SETTLEMENT_SESSION_STATUS.SETTLEMENT_CONFIRMED,
    SETTLEMENT_SESSION_STATUS.RECOVERED
]);

export function canTransitionSettlementStatus(fromStatus, toStatus) {

    const allowed = SETTLEMENT_SESSION_TRANSITIONS[fromStatus] ?? [];

    return allowed.includes(toStatus);

}

export function isSettlementSessionInProgress(status) {

    return IN_PROGRESS_SETTLEMENT_SESSION_STATUSES.includes(status);

}

export function isSettlementSessionTerminal(status) {

    return TERMINAL_SETTLEMENT_SESSION_STATUSES.includes(status);

}
