export const SOCKET_CONNECTION_STATES = Object.freeze({
    DISCONNECTED: "DISCONNECTED",
    CONNECTING: "CONNECTING",
    CONNECTED: "CONNECTED",
    RECONNECTING: "RECONNECTING"
});

export const OUTGOING_SOCKET_EVENTS = Object.freeze({
    PLAYER_READY: "PLAYER_READY",
    PLAYER_READY_CONFIRM: "PLAYER_READY_CONFIRM",
    BUTTON_PRESS: "BUTTON_PRESS",
    BUTTON_RELEASE: "BUTTON_RELEASE",
    PING: "PING",
    PONG: "PONG",
    CLIENT_CONNECTED: "CLIENT_CONNECTED",
    CLIENT_DISCONNECTED: "CLIENT_DISCONNECTED",
    SESSION_RECOVERY_REQUEST: "SESSION_RECOVERY_REQUEST"
});

export const INCOMING_SOCKET_EVENTS = Object.freeze({
    GAME_STATE: "GAME_STATE",
    GAME_CLOCK_UPDATE: "GAME_CLOCK_UPDATE",
    PLAYER_UPDATE: "PLAYER_UPDATE",
    PLAYER_ONLINE: "PLAYER_ONLINE",
    PLAYER_OFFLINE: "PLAYER_OFFLINE",
    WHEEL_CONFIGURATION: "WHEEL_CONFIGURATION",
    PHYSICS_UPDATE: "PHYSICS_UPDATE",
    GAME_RESULT: "GAME_RESULT",
    PAYMENT_STARTED: "PAYMENT_STARTED",
    PAYMENT_COMPLETED: "PAYMENT_COMPLETED",
    PAYMENT_FAILED: "PAYMENT_FAILED",
    AUDIT_STARTED: "AUDIT_STARTED",
    AUDIT_READY: "AUDIT_READY",
    AUDIT_FAILED: "AUDIT_FAILED",
    GAME_START: "GAME_START",
    GAME_END: "GAME_END",
    SETUP_SESSION_STARTED: "SETUP_SESSION_STARTED",
    SETUP_SESSION_SYNC: "SETUP_SESSION_SYNC",
    SETUP_SESSION_EXPIRED: "SETUP_SESSION_EXPIRED",
    VERIFY_COMPLETED: "VERIFY_COMPLETED",
    PAYMENT_STAGE_READY: "PAYMENT_STAGE_READY",
    ENTRY_PAYMENT_SESSION_UPDATED: "ENTRY_PAYMENT_SESSION_UPDATED",
    ENTRY_PAYMENT_COMPLETED: "ENTRY_PAYMENT_COMPLETED",
    WALLET_CONNECTION_SESSION_UPDATED: "WALLET_CONNECTION_SESSION_UPDATED",
    PAYMENT_CONNECTION_READY: "PAYMENT_CONNECTION_READY",
    PAYMENT_SESSION_CREATED: "PAYMENT_SESSION_CREATED",
    PAYMENT_SESSION_UPDATED: "PAYMENT_SESSION_UPDATED",
    PAYMENT_REQUEST: "PAYMENT_REQUEST",
    PAYMENT_SESSION_COMPLETED: "PAYMENT_SESSION_COMPLETED",
    PAYMENT_SESSION_FAILED: "PAYMENT_SESSION_FAILED",
    GAME_CONTRACT_UPDATED: "GAME_CONTRACT_UPDATED",
    GAME_CONTRACT_DEPLOYED: "GAME_CONTRACT_DEPLOYED",
    GAME_CONTRACT_DEPLOY_FAILED: "GAME_CONTRACT_DEPLOY_FAILED",
    // R18 S4 — requester-scoped Deposit package (informational mirror only).
    DEPOSIT_PACKAGE_PUBLISHED: "DEPOSIT_PACKAGE_PUBLISHED",
    // P6.7 — server-owned start gate (Page4 waits; Page5 only on OPEN_PAGE5).
    GAME_START_AUTHORIZED: "GAME_START_AUTHORIZED",
    GAME_INITIALIZING: "GAME_INITIALIZING",
    OPEN_PAGE5: "OPEN_PAGE5",
    OPEN_PAGE6: "OPEN_PAGE6",
    SETTLEMENT_STARTED: "SETTLEMENT_STARTED",
    SETTLEMENT_SUBMITTED: "SETTLEMENT_SUBMITTED",
    SETTLEMENT_CONFIRMED: "SETTLEMENT_CONFIRMED",
    SETTLEMENT_COMPLETED: "SETTLEMENT_COMPLETED",
    SETTLEMENT_FAILED: "SETTLEMENT_FAILED",
    SESSION_FINISHED: "SESSION_FINISHED",
    PING: "PING",
    PONG: "PONG",
    SESSION_SNAPSHOT: "SESSION_SNAPSHOT",
    SESSION_RECOVERY_FAILED: "SESSION_RECOVERY_FAILED",
    PLAYER_INPUT_ACCEPTED: "PLAYER_INPUT_ACCEPTED",
    PLAYER_INPUT_REJECTED: "PLAYER_INPUT_REJECTED",
    PRE_GAME_READY_STARTED: "PRE_GAME_READY_STARTED",
    PRE_GAME_READY_UPDATED: "PRE_GAME_READY_UPDATED",
    PRE_GAME_READY_COMPLETED: "PRE_GAME_READY_COMPLETED"
});

export const SOCKET_MESSAGE_CHANNEL = "game:message";

/** R1.3D — lobby client command (raw socket emit, not game:message). */
export const LOBBY_OUTGOING_EVENTS = Object.freeze({
    DEBUG_START_GAME: "DEBUG_START_GAME",
    /** R6.4 — leave the finished room before client session reset. */
    LEAVE_ROOM: "leaveRoom",
    /** P6.2 — Telegram Wallet / TON Connect reports. */
    WALLET_CONNECT_STARTED: "WALLET_CONNECT_STARTED",
    WALLET_CONNECT_REPORT: "WALLET_CONNECT_REPORT",
    WALLET_DISCONNECT_REPORT: "WALLET_DISCONNECT_REPORT",
    /** R6.11E — forensic autopsy snapshot (does not affect handshake). */
    TONCONNECT_AUTOPSY_SNAPSHOT: "TONCONNECT_AUTOPSY_SNAPSHOT",
    PAYMENT_CONFIRM_INTENT: "PAYMENT_CONFIRM_INTENT",
    PAYMENT_CANCEL_INTENT: "PAYMENT_CANCEL_INTENT",
    /** R12.5G — observation-only Page6 / InfoBar client diagnostics. */
    PAGE6_CLIENT_DIAG: "PAGE6_CLIENT_DIAG"
});
