export const SOCKET_CONNECTION_STATES = Object.freeze({
    DISCONNECTED: "DISCONNECTED",
    CONNECTING: "CONNECTING",
    CONNECTED: "CONNECTED",
    RECONNECTING: "RECONNECTING"
});

export const OUTGOING_SOCKET_EVENTS = Object.freeze({
    PLAYER_READY: "PLAYER_READY",
    PLAYER_READY_CONFIRM: "PLAYER_READY_CONFIRM",
    BUTTON_PRESS: "BUTTON_PRESS",
    BUTTON_RELEASE: "BUTTON_RELEASE",
    PING: "PING",
    PONG: "PONG",
    CLIENT_CONNECTED: "CLIENT_CONNECTED",
    CLIENT_DISCONNECTED: "CLIENT_DISCONNECTED",
    SESSION_RECOVERY_REQUEST: "SESSION_RECOVERY_REQUEST"
});

export const INCOMING_SOCKET_EVENTS = Object.freeze({
    GAME_STATE: "GAME_STATE",
    GAME_CLOCK_UPDATE: "GAME_CLOCK_UPDATE",
    PLAYER_UPDATE: "PLAYER_UPDATE",
    PLAYER_ONLINE: "PLAYER_ONLINE",
    PLAYER_OFFLINE: "PLAYER_OFFLINE",
    WHEEL_CONFIGURATION: "WHEEL_CONFIGURATION",
    PHYSICS_UPDATE: "PHYSICS_UPDATE",
    GAME_RESULT: "GAME_RESULT",
    PAYMENT_STARTED: "PAYMENT_STARTED",
    PAYMENT_COMPLETED: "PAYMENT_COMPLETED",
    PAYMENT_FAILED: "PAYMENT_FAILED",
    AUDIT_STARTED: "AUDIT_STARTED",
    AUDIT_READY: "AUDIT_READY",
    AUDIT_FAILED: "AUDIT_FAILED",
    GAME_START: "GAME_START",
    GAME_END: "GAME_END",
    SETUP_SESSION_STARTED: "SETUP_SESSION_STARTED",
    SETUP_SESSION_SYNC: "SETUP_SESSION_SYNC",
    SETUP_SESSION_EXPIRED: "SETUP_SESSION_EXPIRED",
    VERIFY_COMPLETED: "VERIFY_COMPLETED",
    PAYMENT_STAGE_READY: "PAYMENT_STAGE_READY",
    ENTRY_PAYMENT_SESSION_UPDATED: "ENTRY_PAYMENT_SESSION_UPDATED",
    ENTRY_PAYMENT_COMPLETED: "ENTRY_PAYMENT_COMPLETED",
    OPEN_PAGE5: "OPEN_PAGE5",
    OPEN_PAGE6: "OPEN_PAGE6",
    SESSION_FINISHED: "SESSION_FINISHED",
    PING: "PING",
    PONG: "PONG",
    SESSION_SNAPSHOT: "SESSION_SNAPSHOT",
    SESSION_RECOVERY_FAILED: "SESSION_RECOVERY_FAILED",
    PLAYER_INPUT_ACCEPTED: "PLAYER_INPUT_ACCEPTED",
    PLAYER_INPUT_REJECTED: "PLAYER_INPUT_REJECTED",
    PRE_GAME_READY_STARTED: "PRE_GAME_READY_STARTED",
    PRE_GAME_READY_UPDATED: "PRE_GAME_READY_UPDATED",
    PRE_GAME_READY_COMPLETED: "PRE_GAME_READY_COMPLETED"
});

export const SOCKET_MESSAGE_CHANNEL = "game:message";

/** R1.3D — lobby client command (raw socket emit, not game:message). */
export const LOBBY_OUTGOING_EVENTS = Object.freeze({
    DEBUG_START_GAME: "DEBUG_START_GAME",
    /** R6.4 — leave the finished room before client session reset. */
    LEAVE_ROOM: "leaveRoom"
});
