export const ICON_IDS = Object.freeze({
    DICE: "dice",
    SPADE: "spade",
    QUEEN: "queen",
    LADYBUG: "ladybug",
    HEART: "heart",
    ANCHOR: "anchor",
    STAR: "star",
    DIAMOND: "diamond",
    TURTLE: "turtle",
    SHARK: "shark",
    FOX: "fox",
    OWL: "owl",
    DOLPHIN: "dolphin",
    BUTTERFLY: "butterfly",
    ELEPHANT: "elephant",
    LION: "lion",
    PANDA: "panda",
    RABBIT: "rabbit",
    CAT: "cat",
    DOG: "dog",
    BEAR: "bear",
    FROG: "frog",
    SNAKE: "snake",
    EAGLE: "eagle"
});

export const ICONS = Object.freeze([
    Object.freeze({ id: ICON_IDS.DICE, glyph: "🎲" }),
    Object.freeze({ id: ICON_IDS.SPADE, glyph: "♠" }),
    Object.freeze({ id: ICON_IDS.QUEEN, glyph: "♕" }),
    Object.freeze({ id: ICON_IDS.LADYBUG, glyph: "🐞" }),
    Object.freeze({ id: ICON_IDS.HEART, glyph: "♥" }),
    Object.freeze({ id: ICON_IDS.ANCHOR, glyph: "⚓" }),
    Object.freeze({ id: ICON_IDS.STAR, glyph: "★" }),
    Object.freeze({ id: ICON_IDS.DIAMOND, glyph: "◆" }),
    Object.freeze({ id: ICON_IDS.TURTLE, glyph: "🐢" }),
    Object.freeze({ id: ICON_IDS.SHARK, glyph: "🦈" }),
    Object.freeze({ id: ICON_IDS.FOX, glyph: "🦊" }),
    Object.freeze({ id: ICON_IDS.OWL, glyph: "🦉" }),
    Object.freeze({ id: ICON_IDS.DOLPHIN, glyph: "🐬" }),
    Object.freeze({ id: ICON_IDS.BUTTERFLY, glyph: "🦋" }),
    Object.freeze({ id: ICON_IDS.ELEPHANT, glyph: "🐘" }),
    Object.freeze({ id: ICON_IDS.LION, glyph: "🦁" }),
    Object.freeze({ id: ICON_IDS.PANDA, glyph: "🐼" }),
    Object.freeze({ id: ICON_IDS.RABBIT, glyph: "🐰" }),
    Object.freeze({ id: ICON_IDS.CAT, glyph: "🐱" }),
    Object.freeze({ id: ICON_IDS.DOG, glyph: "🐶" }),
    Object.freeze({ id: ICON_IDS.BEAR, glyph: "🐻" }),
    Object.freeze({ id: ICON_IDS.FROG, glyph: "🐸" }),
    Object.freeze({ id: ICON_IDS.SNAKE, glyph: "🐍" }),
    Object.freeze({ id: ICON_IDS.EAGLE, glyph: "🦅" })
]);
