/**
 * T2.7 — Payment session lifecycle states and transitions.
 */

export const PAYMENT_SESSION_LIFECYCLE_STATUS = Object.freeze({
    CREATED: "CREATED",
    WAITING_FOR_PAYMENTS: "WAITING_FOR_PAYMENTS",
    PARTIALLY_PAID: "PARTIALLY_PAID",
    FULLY_PAID: "FULLY_PAID",
    PAYMENT_TIMEOUT: "PAYMENT_TIMEOUT",
    PAYMENT_FAILED: "PAYMENT_FAILED",
    CANCELLED: "CANCELLED",
    RECOVERED: "RECOVERED"
});

export const PAYMENT_SESSION_TRANSITIONS = Object.freeze({
    [PAYMENT_SESSION_LIFECYCLE_STATUS.CREATED]: Object.freeze([
        PAYMENT_SESSION_LIFECYCLE_STATUS.WAITING_FOR_PAYMENTS,
        PAYMENT_SESSION_LIFECYCLE_STATUS.CANCELLED,
        PAYMENT_SESSION_LIFECYCLE_STATUS.PAYMENT_FAILED
    ]),
    [PAYMENT_SESSION_LIFECYCLE_STATUS.WAITING_FOR_PAYMENTS]: Object.freeze([
        PAYMENT_SESSION_LIFECYCLE_STATUS.PARTIALLY_PAID,
        PAYMENT_SESSION_LIFECYCLE_STATUS.FULLY_PAID,
        PAYMENT_SESSION_LIFECYCLE_STATUS.PAYMENT_TIMEOUT,
        PAYMENT_SESSION_LIFECYCLE_STATUS.PAYMENT_FAILED,
        PAYMENT_SESSION_LIFECYCLE_STATUS.CANCELLED
    ]),
    [PAYMENT_SESSION_LIFECYCLE_STATUS.PARTIALLY_PAID]: Object.freeze([
        PAYMENT_SESSION_LIFECYCLE_STATUS.FULLY_PAID,
        PAYMENT_SESSION_LIFECYCLE_STATUS.PAYMENT_TIMEOUT,
        PAYMENT_SESSION_LIFECYCLE_STATUS.PAYMENT_FAILED,
        PAYMENT_SESSION_LIFECYCLE_STATUS.CANCELLED
    ]),
    [PAYMENT_SESSION_LIFECYCLE_STATUS.RECOVERED]: Object.freeze([
        PAYMENT_SESSION_LIFECYCLE_STATUS.WAITING_FOR_PAYMENTS,
        PAYMENT_SESSION_LIFECYCLE_STATUS.PARTIALLY_PAID,
        PAYMENT_SESSION_LIFECYCLE_STATUS.FULLY_PAID,
        PAYMENT_SESSION_LIFECYCLE_STATUS.PAYMENT_TIMEOUT,
        PAYMENT_SESSION_LIFECYCLE_STATUS.PAYMENT_FAILED,
        PAYMENT_SESSION_LIFECYCLE_STATUS.CANCELLED
    ]),
    [PAYMENT_SESSION_LIFECYCLE_STATUS.FULLY_PAID]: Object.freeze([
        // R7.69C — EMERGENCY_CANCEL allowed on-chain after READY / before SETTLE.
        PAYMENT_SESSION_LIFECYCLE_STATUS.CANCELLED
    ]),
    [PAYMENT_SESSION_LIFECYCLE_STATUS.PAYMENT_TIMEOUT]: Object.freeze([]),
    [PAYMENT_SESSION_LIFECYCLE_STATUS.PAYMENT_FAILED]: Object.freeze([]),
    [PAYMENT_SESSION_LIFECYCLE_STATUS.CANCELLED]: Object.freeze([])
});

export const TERMINAL_PAYMENT_SESSION_STATUSES = Object.freeze([
    PAYMENT_SESSION_LIFECYCLE_STATUS.FULLY_PAID,
    PAYMENT_SESSION_LIFECYCLE_STATUS.PAYMENT_TIMEOUT,
    PAYMENT_SESSION_LIFECYCLE_STATUS.PAYMENT_FAILED,
    PAYMENT_SESSION_LIFECYCLE_STATUS.CANCELLED
]);

export const IN_PROGRESS_PAYMENT_SESSION_STATUSES = Object.freeze([
    PAYMENT_SESSION_LIFECYCLE_STATUS.CREATED,
    PAYMENT_SESSION_LIFECYCLE_STATUS.WAITING_FOR_PAYMENTS,
    PAYMENT_SESSION_LIFECYCLE_STATUS.PARTIALLY_PAID,
    PAYMENT_SESSION_LIFECYCLE_STATUS.RECOVERED
]);

export function canTransitionPaymentStatus(fromStatus, toStatus) {

    const allowed = PAYMENT_SESSION_TRANSITIONS[fromStatus] ?? [];

    return allowed.includes(toStatus);

}

export function isPaymentSessionInProgress(status) {

    return IN_PROGRESS_PAYMENT_SESSION_STATUSES.includes(status);

}

export function isPaymentSessionTerminal(status) {

    return TERMINAL_PAYMENT_SESSION_STATUSES.includes(status);

}
