export const RECOVERY_SOCKET_EVENTS = Object.freeze({
    SESSION_RECOVERY_REQUEST: "SESSION_RECOVERY_REQUEST",
    SESSION_SNAPSHOT: "SESSION_SNAPSHOT",
    SESSION_RECOVERY_FAILED: "SESSION_RECOVERY_FAILED"
});
